version : "3.2"

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            #MYSQL_USER: 'root2'
        ports:
            - 3306:3306
        expose:
            - 3306
        command: mysqld --sql_mode=""
        volumes:
#            - ./databases/my.cnf:/etc/my.cnf:ro
            - ./databases:/docker-entrypoint-initdb.d
#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - 8080:8080
