/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat.FieldWork;

import Models.PBTIndustry;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import parabitccasbharat.Utilities.PBTTextWatchers;

/**
 *
 * @author acer
 */
public class PBTCompInfrastructureDetailsFrame<T> extends JDialog {

    private final PBTIndustry industryData;
    private final HashMap<String, Object> updateMap;
    private final PBTTextWatchers textWatchers;

    /**
     * Creates new form PBTComapnyInfrastructureDetails
     * @param parent
     * @param industryData
     */
    public PBTCompInfrastructureDetailsFrame(T parent,PBTIndustry industryData) {
        super((JDialog)parent,true);
        initComponents();
        updateMap = new HashMap<>();
        this.industryData = industryData;
        this.textWatchers = new PBTTextWatchers();
        updateAllFields();
        addTextWathcers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        areaofcomp = new javax.swing.JTextField();
        mnsrcoflight = new javax.swing.JTextField();
        mainsrcofwaterforindstry = new javax.swing.JTextField();
        mainsrcofdrinkingwater = new javax.swing.JTextField();
        noofwashroom = new javax.swing.JTextField();
        canyes = new javax.swing.JRadioButton();
        canno = new javax.swing.JRadioButton();
        medfacyes = new javax.swing.JRadioButton();
        medfacno = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Area Of company :");

        jLabel2.setText("Main Source Of Light :");

        jLabel3.setText("Main Source Of Water For Industry :");

        jLabel4.setText("AMin Source Of Drinking Water For Industry :");

        jLabel5.setText("No Of Washroom In Compound :");

        jLabel6.setText("Avaiability of Canteen :");

        jLabel7.setText("Avaiability Of Medical Facility In Compund :");

        buttonGroup1.add(canyes);
        canyes.setText("Yes");

        buttonGroup1.add(canno);
        canno.setText("No");
        canno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cannoActionPerformed(evt);
            }
        });

        buttonGroup2.add(medfacyes);
        medfacyes.setText("Yes");

        buttonGroup2.add(medfacno);
        medfacno.setText("No");
        medfacno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medfacnoActionPerformed(evt);
            }
        });

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mnsrcoflight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaofcomp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mainsrcofwaterforindstry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mainsrcofdrinkingwater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noofwashroom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(canyes)
                                .addGap(18, 18, 18)
                                .addComponent(canno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medfacyes)
                                .addGap(18, 18, 18)
                                .addComponent(medfacno)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(areaofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mnsrcoflight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mainsrcofwaterforindstry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mainsrcofdrinkingwater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(noofwashroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medfacyes)
                        .addComponent(medfacno))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(canyes)
                        .addComponent(canno))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cannoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cannoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cannoActionPerformed

    private void medfacnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medfacnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medfacnoActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String query = industryData.toUpdateQuery(updateMap);
        industryData.update(query);
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaofcomp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton canno;
    private javax.swing.JRadioButton canyes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mainsrcofdrinkingwater;
    private javax.swing.JTextField mainsrcofwaterforindstry;
    private javax.swing.JRadioButton medfacno;
    private javax.swing.JRadioButton medfacyes;
    private javax.swing.JTextField mnsrcoflight;
    private javax.swing.JTextField noofwashroom;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    private void updateAllFields() {
        if(industryData.getAreaofcomp()!=null){
            areaofcomp.setText(industryData.getAreaofcomp());
        }
        if(industryData.getMainsrclight()!=null){
            mnsrcoflight.setText(industryData.getMainsrclight());
        }
        if(industryData.getMainsrc_watforindus()!=null){
            mainsrcofwaterforindstry.setText(industryData.getMainsrc_watforindus());
        }
        if(industryData.getMainsrc_drnkwat_inindus()!=null){
            mainsrcofdrinkingwater.setText(industryData.getMainsrc_drnkwat_inindus());
        }
        if(industryData.getNoofwash_inindus()!=null){
            noofwashroom.setText("" + industryData.getNoofwash_inindus());
        }
        if(industryData.getAvbofmedfac_insdcomp()!=null){
            if (industryData.getAvbofmedfac_insdcomp().equals("Y")){
                medfacyes.setSelected(true);
            }else{
                medfacno.setSelected(true);
            }
        }
        if(industryData.getAvbofcant()!=null){
            if (industryData.getAvbofcant().equals("Y")){
                canyes.setSelected(true);
            }else{
                canno.setSelected(true);
            }
        }
    }

    private void addTextWathcers() {
        textWatchers.addNameNumberTextWatcher(areaofcomp, updateMap, "AreaOfComp");
        textWatchers.addNumberTextWatcher(noofwashroom, updateMap, "NoOfWash_inIndus");
        textWatchers.addYesNolistener(medfacyes, medfacno, updateMap, "AvbOfMedFac_InsdComp");
        textWatchers.addYesNolistener(canyes, canno, updateMap, "AvbOfCant");
    }
}
