/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat.FieldWork;

import Models.PBTIndustry;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import parabitccasbharat.Utilities.PBTTextWatchers;

/**
 *
 * @author acer
 */
public class PBTCompFinancialDeailsFrame<T> extends JDialog {

    private final PBTIndustry industryData;
    private final HashMap<String, Object> updateMap;
    private final PBTTextWatchers textWatchers;
    /**
     * Creates new form PBTCompanyFinancialDeails
     * @param parent
     * @param industryData
     */
    public PBTCompFinancialDeailsFrame(T parent,PBTIndustry industryData) {
        super((JDialog)parent,true);
        initComponents();
        updateMap = new HashMap<>();
        this.industryData = industryData;
        textWatchers = new PBTTextWatchers();
        updateAllFields();
        addTextWathcers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmpaccno = new javax.swing.JTextField();
        cmpowneraccnum = new javax.swing.JTextField();
        turnoverofcomp = new javax.swing.JTextField();
        finalprodofcomp = new javax.swing.JTextField();
        minsaleofcmp = new javax.swing.JTextField();
        maxsaleofcomp = new javax.swing.JTextField();
        gstno = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Company Account No :");

        jLabel2.setText("Comany Owner Account Number :");

        jLabel3.setText("Turn Over Of Company :");

        jLabel4.setText("Final Production Of Company :");

        jLabel5.setText("Minimum Sale Of Comapny :");

        jLabel6.setText("Maximum Sale Of Comapny :");

        jLabel7.setText("GST No :");

        maxsaleofcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxsaleofcompActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmpaccno)
                            .addComponent(cmpowneraccnum)
                            .addComponent(turnoverofcomp)
                            .addComponent(finalprodofcomp)
                            .addComponent(minsaleofcmp)
                            .addComponent(maxsaleofcomp)
                            .addComponent(gstno, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmpaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(cmpowneraccnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(turnoverofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(finalprodofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(minsaleofcmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maxsaleofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gstno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maxsaleofcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxsaleofcompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxsaleofcompActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String query = industryData.toUpdateQuery(updateMap);
        industryData.update(query);
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmpaccno;
    private javax.swing.JTextField cmpowneraccnum;
    private javax.swing.JTextField finalprodofcomp;
    private javax.swing.JTextField gstno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField maxsaleofcomp;
    private javax.swing.JTextField minsaleofcmp;
    private javax.swing.JButton save;
    private javax.swing.JTextField turnoverofcomp;
    // End of variables declaration//GEN-END:variables

    private void updateAllFields() {
        if(industryData.getCompano()!=null){
            cmpaccno.setText(industryData.getCompano());
        }
        if(industryData.getCompownrano()!=null){
            cmpowneraccnum.setText(industryData.getCompownrano());
        }
        if(industryData.getTurnoverofcomp()!=null){
            turnoverofcomp.setText("" + industryData.getTurnoverofcomp());
        }
        if(industryData.getFnlprodofcomp()!=null){
            finalprodofcomp.setText(industryData.getFnlprodofcomp());
        }
        if(industryData.getMinsalofcomp()!=null){
            minsaleofcmp.setText("" + industryData.getMinsalofcomp());
        }
        if(industryData.getMaxsalofcomp()!=null){
            maxsaleofcomp.setText("" + industryData.getMaxsalofcomp());
        }
        if(industryData.getGstno()!=null){
            gstno.setText(industryData.getGstno());
        }
    }

    private void addTextWathcers() {
        textWatchers.addNumberTextWatcher(cmpaccno, updateMap, "CompANo");
        textWatchers.addNumberTextWatcher(cmpowneraccnum, updateMap, "CompOwnrANo");
        textWatchers.addNumberTextWatcher(turnoverofcomp, updateMap, "TurnOverOfComp");
        textWatchers.addNameNumberTextWatcher(finalprodofcomp, updateMap, "FnlProdOfComp");
        textWatchers.addNumberTextWatcher(minsaleofcmp, updateMap, "MinSalOfComp");
        textWatchers.addNumberTextWatcher(maxsaleofcomp, updateMap, "MaxSalOfComp");
        textWatchers.addNameNumberTextWatcher(gstno, updateMap, "GSTNo");
    }
}
