/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat.FieldWork;

import Models.PBTIndustry;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import parabitccasbharat.Utilities.PBTTextWatchers;

/**
 *
 * @author acer
 */
public class PBTCompLocationDeatilsFrame<T> extends JDialog {

    private final PBTIndustry industryData;
    private final HashMap<String, Object> updateMap;
    private final PBTTextWatchers textWatchers;

    /**
     * Creates new form PBTCompLocarionDeatilsFrame
     * @param parent
     * @param industryData
     */
    public PBTCompLocationDeatilsFrame(T parent,PBTIndustry industryData) {
        super((JDialog)parent,true);
        initComponents();
        updateMap = new HashMap<>();
        this.industryData = industryData;
        this.textWatchers = new PBTTextWatchers();
        updateAllFields();
        addTextWathcers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nrstpolstation = new javax.swing.JTextField();
        nrsthospital = new javax.swing.JTextField();
        nrstfirebrigade = new javax.swing.JTextField();
        nrstrailwaystation = new javax.swing.JTextField();
        nrstbusstop = new javax.swing.JTextField();
        nrstairport = new javax.swing.JTextField();
        nrsttransportair = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nearest Police Station :");

        jLabel2.setText("Nearest Hospital :");

        jLabel3.setText("Nearest FireBrigade :");

        jLabel4.setText("Nearest Railway Station :");

        jLabel5.setText("Nearest Bus Stop :");

        jLabel6.setText("Nearest Aiirport :");

        jLabel7.setText("Nearest TransportAr :");

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nrstpolstation)
                            .addComponent(nrsthospital)
                            .addComponent(nrstfirebrigade)
                            .addComponent(nrstrailwaystation)
                            .addComponent(nrstbusstop)
                            .addComponent(nrstairport)
                            .addComponent(nrsttransportair, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nrstpolstation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(nrsthospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nrstfirebrigade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nrstrailwaystation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nrstbusstop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nrstairport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nrsttransportair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String query = industryData.toUpdateQuery(updateMap);
        industryData.update(query);
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nrstairport;
    private javax.swing.JTextField nrstbusstop;
    private javax.swing.JTextField nrstfirebrigade;
    private javax.swing.JTextField nrsthospital;
    private javax.swing.JTextField nrstpolstation;
    private javax.swing.JTextField nrstrailwaystation;
    private javax.swing.JTextField nrsttransportair;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    private void updateAllFields() {
        if(industryData.getNearestps()!=null){
            nrstpolstation.setText(industryData.getNearestps());
        }
        if(industryData.getNearesthsp()!=null){
            nrsthospital.setText(industryData.getNearesthsp());
        }
        if(industryData.getNearestfirebrgd()!=null){
            nrstfirebrigade.setText(industryData.getNearestfirebrgd());
        }
        if(industryData.getNearestrail()!=null){
            nrstrailwaystation.setText(industryData.getNearestrail());
        }
        if(industryData.getNearestbusstp()!=null){
            nrstbusstop.setText(industryData.getNearestbusstp());
        }
        if(industryData.getNearestarprt()!=null){
            nrstairport.setText(industryData.getNearestarprt());
        }
        if(industryData.getNearesttrnsprtar()!=null){
            nrsttransportair.setText(industryData.getNearesttrnsprtar());
        }
    }

    private void addTextWathcers() {
        textWatchers.addNameTextWatcher(nrstpolstation, updateMap, "NearestPS");
        textWatchers.addNameTextWatcher(nrsthospital, updateMap, "NearestHsp");
        textWatchers.addNameTextWatcher(nrstfirebrigade, updateMap, "NearestFireBrgd");
        textWatchers.addNameTextWatcher(nrstrailwaystation, updateMap, "NearestRail");
        textWatchers.addNameTextWatcher(nrstbusstop, updateMap, "NearestBusStp");
        textWatchers.addNameTextWatcher(nrstairport, updateMap, "NearestArprt");
        textWatchers.addNameTextWatcher(nrsttransportair, updateMap, "NearestTrnsprtAr");
    }
}
