
package parabitccasbharat.FieldWork;

import Models.PBTHouseListingModel;
import parabitccasbharat.Utilities.PBTTextWatchers;
import java.util.HashMap;
import javax.swing.JFrame;
import parabitccasbharat.Utilities.PBTGenericDisease;
import parabitccasbharat.Utilities.PBTUtilities;

public class PBTGeneralInfoDashBoard<T> extends javax.swing.JDialog {

    PBTHouseListingModel houselistingdata;
    PBTTextWatchers textwatcher;
    HashMap<String, Object> updatemap = new HashMap<>();
    public PBTGeneralInfoDashBoard(PBTHouseListingModel houselistingdata,T parent) {
        super((JFrame)parent,true);
        initComponents();
        this.textwatcher = new PBTTextWatchers();
        this.houselistingdata = houselistingdata;
        addTextWatchers();
        setAllLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        geneticdisease = new javax.swing.JTextField();
        nearesthospdis = new javax.swing.JTextField();
        deathinpast = new javax.swing.JTextField();
        reasonofdeath = new javax.swing.JTextField();
        deathagegrp = new javax.swing.JTextField();
        firstaidyes = new javax.swing.JRadioButton();
        firstaidno = new javax.swing.JRadioButton();
        insuranceyes = new javax.swing.JRadioButton();
        Insuranceno = new javax.swing.JRadioButton();
        lifeinsyes = new javax.swing.JRadioButton();
        lifeinsno = new javax.swing.JRadioButton();
        geninsyes = new javax.swing.JRadioButton();
        geninsno = new javax.swing.JRadioButton();
        courtcaseyes = new javax.swing.JRadioButton();
        courtcaseno = new javax.swing.JRadioButton();
        fincaseyes = new javax.swing.JRadioButton();
        fincaseno = new javax.swing.JRadioButton();
        foriegndisyes = new javax.swing.JRadioButton();
        foriendisputeno = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Genetic Disease In Family :");

        jLabel2.setText("First Aid Available :");

        jLabel3.setText("Health Insurance of Individual :");

        jLabel4.setText("Life Insurance Of Individual :");

        jLabel5.setText("General Insurance Of Individual :");

        jLabel6.setText("Any Court Case on Fammily :");

        jLabel7.setText("Any Financial Case :");

        jLabel8.setText("Any Foreign Dispute in Family :");

        jLabel9.setText("Nearest Hospital Distance :");

        jLabel10.setText("Death In Past 10 Years :");

        jLabel11.setText("Reason Of Death :");

        jLabel12.setText("Death Age Group :");

        geneticdisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneticdiseaseActionPerformed(evt);
            }
        });

        buttonGroup1.add(firstaidyes);
        firstaidyes.setText("Yes");

        buttonGroup1.add(firstaidno);
        firstaidno.setText("No");

        buttonGroup2.add(insuranceyes);
        insuranceyes.setText("Yes");

        buttonGroup2.add(Insuranceno);
        Insuranceno.setText("No");

        buttonGroup3.add(lifeinsyes);
        lifeinsyes.setText("Yes");

        buttonGroup3.add(lifeinsno);
        lifeinsno.setText("No");

        buttonGroup4.add(geninsyes);
        geninsyes.setText("Yes");

        buttonGroup4.add(geninsno);
        geninsno.setText("No");

        buttonGroup5.add(courtcaseyes);
        courtcaseyes.setText("Yes");

        buttonGroup5.add(courtcaseno);
        courtcaseno.setText("No");

        buttonGroup6.add(fincaseyes);
        fincaseyes.setText("Yes");

        buttonGroup6.add(fincaseno);
        fincaseno.setText("No");

        buttonGroup7.add(foriegndisyes);
        foriegndisyes.setText("Yes");

        buttonGroup7.add(foriendisputeno);
        foriendisputeno.setText("No");

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstaidyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstaidno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insuranceyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Insuranceno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lifeinsyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lifeinsno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(geninsyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(geninsno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(courtcaseyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(courtcaseno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fincaseyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fincaseno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foriegndisyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foriendisputeno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(geneticdisease, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deathagegrp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(reasonofdeath, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deathinpast, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nearesthospdis, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(58, 58, 58)
                        .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(geneticdisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstaidyes)
                        .addComponent(firstaidno)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insuranceyes)
                    .addComponent(Insuranceno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lifeinsyes)
                    .addComponent(lifeinsno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(geninsyes)
                    .addComponent(geninsno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(courtcaseyes)
                    .addComponent(courtcaseno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fincaseyes)
                    .addComponent(fincaseno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(foriegndisyes)
                    .addComponent(foriendisputeno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nearesthospdis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(deathinpast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(reasonofdeath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(deathagegrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PBTGenericDisease frame = new PBTGenericDisease(houselistingdata, this);
        frame.setVisible(true);
        geneticdisease.setText(PBTUtilities.getTypesofgeneticdisease(houselistingdata.getGendiss()));
        updatemap.put("Gendiss", houselistingdata.getGendiss());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        System.out.println(houselistingdata.toUpdateQuery(updatemap));
        houselistingdata.update(houselistingdata.toUpdateQuery(updatemap));
        houselistingdata.getFromhlsno(houselistingdata.getHl_sno());
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    private void geneticdiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geneticdiseaseActionPerformed
        System.out.println(houselistingdata.toUpdateQuery(updatemap));
        houselistingdata.update(houselistingdata.toUpdateQuery(updatemap));
        houselistingdata.getFromhlsno(houselistingdata.getHl_sno());
        this.dispose();
    }//GEN-LAST:event_geneticdiseaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBTGeneralInfoDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBTGeneralInfoDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBTGeneralInfoDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBTGeneralInfoDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PBTGeneralInfoDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Insuranceno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JRadioButton courtcaseno;
    private javax.swing.JRadioButton courtcaseyes;
    private javax.swing.JTextField deathagegrp;
    private javax.swing.JTextField deathinpast;
    private javax.swing.JRadioButton fincaseno;
    private javax.swing.JRadioButton fincaseyes;
    private javax.swing.JRadioButton firstaidno;
    private javax.swing.JRadioButton firstaidyes;
    private javax.swing.JRadioButton foriegndisyes;
    private javax.swing.JRadioButton foriendisputeno;
    private javax.swing.JTextField geneticdisease;
    private javax.swing.JRadioButton geninsno;
    private javax.swing.JRadioButton geninsyes;
    private javax.swing.JRadioButton insuranceyes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton lifeinsno;
    private javax.swing.JRadioButton lifeinsyes;
    private javax.swing.JTextField nearesthospdis;
    private javax.swing.JTextField reasonofdeath;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    private void addTextWatchers() {
        textwatcher.addYesNolistener(firstaidyes, firstaidno, updatemap, "Firstaidkit");
        textwatcher.addYesNolistener(insuranceyes, Insuranceno, updatemap, "H_insu");
        textwatcher.addYesNolistener(lifeinsyes, lifeinsno, updatemap, "L_insu");
        textwatcher.addYesNolistener(geninsyes, geninsno, updatemap, "G_insu");
        textwatcher.addYesNolistener(courtcaseyes, courtcaseno, updatemap, "Courtcase");
        textwatcher.addYesNolistener(fincaseyes, fincaseno, updatemap, "Fincase");
        textwatcher.addYesNolistener(foriegndisyes, foriendisputeno, updatemap, "Foreigndispute");
        textwatcher.addNumberTextWatcher(nearesthospdis, updatemap, "Nhospdist");
        textwatcher.addNumberTextWatcher(deathinpast, updatemap, "Deathin10years");
        textwatcher.addNameTextWatcher(reasonofdeath, updatemap, "Reasonofdeath");
        textwatcher.addNumberTextWatcher(deathagegrp, updatemap, "Deathagegroup");
    }

    private void setAllLabels() {
        if(houselistingdata.getGendiss()!=null){
            geneticdisease.setText(houselistingdata.getGendiss());
        }
        if(houselistingdata.getFirstaidkit()!=null){
            if(houselistingdata.getFirstaidkit().equals("Y")){
                firstaidyes.setSelected(true);
            }else{
                firstaidno.setSelected(true);
            }
        }
        if(houselistingdata.getH_insu()!=null){
            if(houselistingdata.getH_insu().equals("Y")){
                insuranceyes.setSelected(true);
            }else{
                Insuranceno.setSelected(true);
            }
        }
        if(houselistingdata.getL_insu()!=null){
            if(houselistingdata.getL_insu().equals("Y")){
                lifeinsyes.setSelected(true);
            }else{
                lifeinsno.setSelected(true);
            }
        }
        if(houselistingdata.getG_insu()!=null){
            if(houselistingdata.getG_insu().equals("Y")){
                geninsyes.setSelected(true);
            }else{
                geninsno.setSelected(true);
            }
        }
        if(houselistingdata.getCourtcase()!=null){
            if(houselistingdata.getCourtcase().equals("Y")){
                courtcaseyes.setSelected(true);
            }else{
                courtcaseno.setSelected(true);
            }
        }
        if(houselistingdata.getFincase()!=null){
            if(houselistingdata.getFincase().equals("Y")){
                fincaseyes.setSelected(true);
            }else{
                fincaseno.setSelected(true); 
            }
        }
        if(houselistingdata.getForeigndispute()!=null){
            if(houselistingdata.getForeigndispute().equals("Y")){
               foriegndisyes.setSelected(true);
            }else{
                foriendisputeno.setSelected(true); 
            }
        }
        if(houselistingdata.getNhospdist()!=null){
            nearesthospdis.setText(houselistingdata.getNhospdist());
        }
        if(houselistingdata.getDeathin10years()!=0){
            deathinpast.setText("" + houselistingdata.getDeathin10years());
        }
        if(houselistingdata.getReasonofdeath()!=null){
            reasonofdeath.setText(houselistingdata.getReasonofdeath());
        }
        if(houselistingdata.getDeathagegroup()!=null){
            deathagegrp.setText(houselistingdata.getDeathagegroup());
        }
    }

}
