/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat.FieldWork;

import Models.PBTHouseHoldModel;
import parabitccasbharat.Utilities.PBTTextWatchers;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class PBTOthersFrame<T> extends javax.swing.JDialog {
    
    PBTHouseHoldModel persondata;
    PBTTextWatchers textWatchers;
    HashMap<String, Object> updatemap = new HashMap<>();
    public PBTOthersFrame(PBTHouseHoldModel persondata,T parent) {
        super((JFrame)parent,true);
        initComponents();
        this.persondata = persondata;
        textWatchers = new PBTTextWatchers();
        addTextWatchers();
        getAllLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        birthplace = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        house = new javax.swing.JTextField();
        ward = new javax.swing.JTextField();
        town = new javax.swing.JTextField();
        tehsil = new javax.swing.JTextField();
        district = new javax.swing.JTextField();
        pincode = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nriyes = new javax.swing.JRadioButton();
        nrino = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reasonofmigration = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        timeofmigration = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        foriegnadress = new javax.swing.JTextField();
        courtcaseyes = new javax.swing.JRadioButton();
        courtcaseno = new javax.swing.JRadioButton();
        fincaseyes = new javax.swing.JRadioButton();
        fincaseno = new javax.swing.JRadioButton();
        foriegndisyes = new javax.swing.JRadioButton();
        foriendisputeno = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Birth Place With State And Country : ");

        jLabel2.setText("Permanent Adress Details : ");

        jLabel3.setText("House.no/Street/Locality : ");

        jLabel4.setText("Ward No :");

        jLabel5.setText("Town Village :");

        jLabel6.setText("Tehsil :");

        jLabel7.setText("District :");

        jLabel8.setText("Pincode :");

        jLabel9.setText("State :");

        jLabel10.setText("NRI :");

        buttonGroup1.add(nriyes);
        nriyes.setText("Yes");
        nriyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nriyesActionPerformed(evt);
            }
        });

        buttonGroup1.add(nrino);
        nrino.setText("No");
        nrino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrinoActionPerformed(evt);
            }
        });

        jLabel11.setText("Foriegn Adress :");

        jLabel12.setText("Reason Of Migration :");

        jLabel13.setText("Time Period Of Migration :");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        courtcaseyes.setText("Yes");

        courtcaseno.setText("No");

        fincaseyes.setText("Yes");

        fincaseno.setText("No");

        foriegndisyes.setText("Yes");

        foriendisputeno.setText("No");

        jLabel14.setText("Any Court Case on Fammily :");

        jLabel15.setText("Any Financial Case :");

        jLabel16.setText("Any Foreign Dispute in Family :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(house, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ward)
                                .addComponent(town)
                                .addComponent(tehsil)
                                .addComponent(district)
                                .addComponent(pincode)
                                .addComponent(state, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nriyes)
                                .addGap(18, 18, 18)
                                .addComponent(nrino))
                            .addComponent(reasonofmigration)
                            .addComponent(foriegnadress)
                            .addComponent(timeofmigration, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(courtcaseyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(courtcaseno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fincaseyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fincaseno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foriegndisyes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(foriendisputeno)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(courtcaseyes)
                            .addComponent(courtcaseno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(fincaseyes)
                            .addComponent(fincaseno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(foriegndisyes)
                            .addComponent(foriendisputeno))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(town, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nriyes)
                                .addComponent(nrino)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(foriegnadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(reasonofmigration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(timeofmigration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nriyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nriyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nriyesActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        System.out.println(persondata.toUpdateQuery(updatemap));
        persondata.update(persondata.toUpdateQuery(updatemap));
        persondata.getDataFromAadhar(persondata.getUid());
        this.dispose();
    }//GEN-LAST:event_SaveActionPerformed

    private void nrinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBTOthersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBTOthersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBTOthersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBTOthersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PBTOthersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JTextField birthplace;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton courtcaseno;
    private javax.swing.JRadioButton courtcaseyes;
    private javax.swing.JTextField district;
    private javax.swing.JRadioButton fincaseno;
    private javax.swing.JRadioButton fincaseyes;
    private javax.swing.JTextField foriegnadress;
    private javax.swing.JRadioButton foriegndisyes;
    private javax.swing.JRadioButton foriendisputeno;
    private javax.swing.JTextField house;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton nrino;
    private javax.swing.JRadioButton nriyes;
    private javax.swing.JTextField pincode;
    private javax.swing.JTextField reasonofmigration;
    private javax.swing.JTextField state;
    private javax.swing.JTextField tehsil;
    private javax.swing.JTextField timeofmigration;
    private javax.swing.JTextField town;
    private javax.swing.JTextField ward;
    // End of variables declaration//GEN-END:variables

    private void addTextWatchers() {
        textWatchers.addNameTextWatcher(birthplace, updatemap, "Birthplacewithstatecountry");
        textWatchers.addNameTextWatcher(house, updatemap, "Pmthnoadd");
        textWatchers.addNameTextWatcher(town, updatemap, "Pmttownvillage");
        textWatchers.addNameTextWatcher(tehsil, updatemap, "Pmttehsil");
        textWatchers.addNameTextWatcher(district, updatemap, "Pmtdist");
        textWatchers.addNumberTextWatcher(pincode, updatemap, "Pmtpincode");
        textWatchers.addNameTextWatcher(state, updatemap, "Pmtstut");
        textWatchers.addNameTextWatcher(foriegnadress, updatemap, "Foreignadd");
        textWatchers.addNameTextWatcher(reasonofmigration, updatemap, "Rsnofmig");
        textWatchers.addNumberTextWatcher(timeofmigration, updatemap, "Durofmig");
        textWatchers.addNumberTextWatcher(ward, updatemap, "Pmtwardno");
        textWatchers.addYesNolistener(courtcaseyes, courtcaseno, updatemap, "Courtcase");
        textWatchers.addYesNolistener(fincaseyes, fincaseno, updatemap, "Fincase");
        textWatchers.addYesNolistener(foriegndisyes, foriendisputeno, updatemap, "Foreigndispute");
        nriyes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //System.out.println("Yes");
                updatemap.put("Nri", "Y");
                isNri(true);
            }
        });
        nrino.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //System.out.println("No");
                updatemap.put("Nri", "N");
                isNri(false);
            }
        });
    }

    private void getAllLabels() {
        if(persondata.getBirthplacewithstatecountry()!=null){
            birthplace.setText(persondata.getBirthplacewithstatecountry());
        }
        if(persondata.getPmthnoadd()!=null){
            house.setText(persondata.getPmthnoadd());
        }
        if(persondata.getPmtwardno()!=null){
            ward.setText(persondata.getPmtwardno());
        }
        if(persondata.getPmttehsil()!=null){
            tehsil.setText(persondata.getPmttehsil());
        }
        if(persondata.getPmtpincode()!=null){
            pincode.setText(persondata.getPmtpincode());
        }
        if(persondata.getPmttownvillage()!=null){
            town.setText(persondata.getPmttownvillage());
        }
        if(persondata.getPmtdist()!=null){
            district.setText(persondata.getPmtdist());
        }
        if(persondata.getPmtstut()!=null){
            state.setText(persondata.getPmtstut());
        }
        if(persondata.getForeignadd()!=null){
            foriegnadress.setText(persondata.getForeignadd());
        }
        if(persondata.getRsnofmig()!=null){
            reasonofmigration.setText(persondata.getRsnofmig());
        }
        if(persondata.getDurofmig()!=null){
            timeofmigration.setText(persondata.getDurofmig());
        }
        if(persondata.getCourtcase()!=null){
            if(persondata.getCourtcase().equals("Y")){
                courtcaseyes.setSelected(true);
            }else{
                courtcaseno.setSelected(true);
            }
        }
        if(persondata.getFincase()!=null){
            if(persondata.getFincase().equals("Y")){
                fincaseyes.setSelected(true);
            }else{
                fincaseno.setSelected(true); 
            }
        }
        if(persondata.getForeigndispute()!=null){
            if(persondata.getForeigndispute().equals("Y")){
               foriegndisyes.setSelected(true);
            }else{
                foriendisputeno.setSelected(true); 
            }
        }
        if(persondata.getNri()!=null){
            if(persondata.getNri().equals("Y")){
                nriyes.setSelected(true);
                isNri(true);
            }else {
                nrino.setSelected(true);
                isNri(false);
            }
        }
    }
    
    public void isNri(Boolean Visibility){
        jLabel11.setVisible(Visibility);
        jLabel12.setVisible(Visibility);
        jLabel13.setVisible(Visibility);
        reasonofmigration.setVisible(Visibility);
        foriegnadress.setVisible(Visibility);
        timeofmigration.setVisible(Visibility);
        if(!Visibility){
            updatemap.remove("Rsnofmig");
            updatemap.remove("Foreignadd");
            updatemap.remove("Durofmig");
            reasonofmigration.setText("");
            foriegnadress.setText("");
            timeofmigration.setText("");
        }
    }
}
