/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class PBTAppointedEmp extends javax.swing.JDialog {

    ParabitDBC db;
    PBTDataOfEmployee data;
    public PBTAppointedEmp(PBTDataOfEmployee data,PBTManageEmp parent) {
        super(parent,true);
        initComponents();
        this.data = data;
        db = new ParabitDBC();
        fetchemployes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEID", "GEID", "Name", "Grade", "MobileNo", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void fetchemployes() {
        String query = "SELECT * FROM `pbtemployeetable2` where grade = '" + (data.getGrade()+1) + "'";
        switch(data.getGrade())
        {
            case 1:
                break;
            case 4:
                query = query + " and Areacity = '" + data.getAreacity() + "'" ;
            case 3:
                query = query + " and Areadist = '" + data.getAreadist() + "'" ;
            case 2:
                query = query + " and Areastate = '" + data.getAreastate() + "'" ;
                break;
            default:
                break;
        }
        System.out.println(query);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            db.rs1 = db.stm.executeQuery(query);
            while(db.rs1.next())
            {
                String ceid = db.rs1.getString("CEID");
                String geid = db.rs1.getString("GEID");
                String name = db.rs1.getString("EmpName");
                int grade = db.rs1.getInt("Grade");
                String email = db.rs1.getString("Email");
                String mob = db.rs1.getString("EmpOffMob");
                Object row[] = {ceid,geid,name,grade,mob,email};
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
