/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat.OfficeWork;

import Models.PBTDataOfEmployee;
import java.awt.Color;
import parabitccasbharat.Custom.RoundedPanel;
import parabitccasbharat.PBTCurrentEmp;

/**
 *
 * @author acer
 */
public class PBTManageEmployee extends RoundedPanel {

    /**
     * Creates new form PBTManageEmployee
     */
    PBTDataOfEmployee data;
    PBTOfficeMainDashBoard dashboard;
    public PBTManageEmployee(PBTOfficeMainDashBoard dashboard) {
        super(15, Color.GREEN);
        initComponents();
        this.data = PBTCurrentEmp.getEmployeeData();
        this.dashboard = dashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newappoint = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        appointed = new javax.swing.JButton();

        newappoint.setText("New Appointment");
        newappoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newappointActionPerformed(evt);
            }
        });

        transfer.setText("Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        appointed.setText("Appointed Employee");
        appointed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(newappoint)
                    .addGap(18, 18, 18)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(appointed)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newappoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(appointed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newappointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newappointActionPerformed
        PBTNewAppointment appoint = new PBTNewAppointment(dashboard);
        appoint.setVisible(true);
    }//GEN-LAST:event_newappointActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        PBTAppointedEmp appointed = new PBTAppointedEmp(dashboard,2);
        appointed.setVisible(true);
    }//GEN-LAST:event_transferActionPerformed

    private void appointedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointedActionPerformed
        PBTAppointedEmp appointed = new PBTAppointedEmp(dashboard,1);
        appointed.setVisible(true);
    }//GEN-LAST:event_appointedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointed;
    private javax.swing.JButton newappoint;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
