package TestingSummary;

import DB.ParabitDBC;
import java.awt.BorderLayout;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import static parabitccasbharat.OfficeWork.DatabsePieChartFrame.TABLE_NAME;

public class SexRatioPanel extends javax.swing.JPanel {

    String columnName = "Gender";
    static DefaultPieDataset piedataset = new DefaultPieDataset();
    PiePlot chartplot;
    ParabitDBC db;
    public SexRatioPanel() {
        initComponents();
        db = new ParabitDBC();
        JFreeChart chart = getChart();
        ChartPanel panel = new ChartPanel(chart);
        chartplot = (PiePlot) chart.getPlot();
        add(panel,BorderLayout.CENTER);
        addValuesOfDB();
        designChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private JFreeChart getChart() {
        return ChartFactory.createPieChart("PieChart", piedataset, true, true, false);
    }

    private void addValuesOfDB() {
        piedataset.clear();
        String query = "SELECT " + columnName + " FROM `" + TABLE_NAME + "`";
        try {
            db.rs1 = db.stm.executeQuery(query);
            int y=0,n=0;
            while(db.rs1.next()){
                String key = db.rs1.getString(1);
                if(key != null && !key.isEmpty()){
                    try{
                        if(key.equals("M")) y++; else n++;
                        piedataset.setValue( key ,piedataset.getValue(key).intValue() + 1 );
                    }catch(Exception e){
                        piedataset.setValue( key , 0 );
                    }
                }
            }
            System.out.println(y + " " + n);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void designChart() {
        chartplot.setBackgroundAlpha(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
